### ISSUE TITLE
Formbuilder without alpacaJS

### ISSUE THREAD

**Issue by felix-mueller** [fernandosam/formbuilder#1]
Hey,
I really like the formbuilder and it's a useful tool. Just one idea from my side:
Do you think it would be possible to generate output without using alpacaJS? In Camunda tasklist there are already a few JS frameworks included and I don't like the idea of adding another one just for forms. I would prefer to get raw HTML + JS that you can just copy into the embedded forms. This would also allow to make small changes directly in HTML / JS. What do you think about this idea?

**Comment by fernandosam** [comment]
Hy Felix. It's a excellent idea, but the actual project is tightly coupled with AlpacaJS. All the actual project use AlpacaJS (from formbuilder to code generate).
I will provide a tutorial in english to explain how to integrate alpacajs with Camunda.
Thanks.

**Comment by zirconias** [comment]
hey @fernandosam   would love to see the tutorial explain how to integrate the formbuilder with camunda. thanks.

**Comment by fernandosam** [comment]
I translated the tutorial to english.
